/* Phrase library for tabletop scribing. Categories of ready-to-render lines. */
window.PHRASES = [
  { cat: 'Warnings & Wards', items: [
    'Turn back or be unmade',
    'The seal must never break',
    'Beyond this door the dead keep watch',
    'No light returns from below',
    'Speak no name within these halls',
    'The price of entry is everything',
    'Wake not what the mountain buried',
    'Trespassers feed the garden',
    'Here ends the road of the living',
    'The third step lies',
    'Touch nothing that glitters',
    'It counts your heartbeats',
    'The water remembers every face',
    'Sealed by order of the last king',
    'Do not answer when it knocks',
    'The hungry dark is patient',
    'Leave an offering or leave a finger',
    'This bridge has a toll and a temper',
    'Past this stone, your gods are deaf',
    'Run before moonrise'
  ] },
  { cat: 'Tomb & Memorial', items: [
    'Here lies the breaker of chains',
    'She traded her name for our dawn',
    'First into the breach, last to fall',
    'A king in life, a warning in death',
    'He owed death a debt and paid twice',
    'Beloved traitor, honored thief',
    'The mountain keeps her now',
    'Forged in war, finished in peace',
    'Wake him only at the end of all things',
    'Built by the hands he freed',
    'Her song outlived the empire',
    'Ash to root, root to crown',
    'He asked for no monument; we lied',
    'Ten thousand candles, one flame',
    'Sleep, old wolf, the flock is safe',
    'What we bury here is not forgotten',
    'The last of the dawn-keepers',
    'Beneath this stone, the storm rests'
  ] },
  { cat: 'Prophecy & Omen', items: [
    'When the twin moons kiss, the gate remembers',
    'A crown of ash for the third-born',
    'The river will run backward to warn you',
    'One door opens only to the broken',
    'The pale comet brings a hungry year',
    'From the sundered vault, the old hunger wakes',
    'Three lies will save the city',
    'The blind one sees the way out',
    'Iron sleeps until the ninth bell',
    'A stranger carries the last ember',
    'When wolves sing at noon, kings should listen',
    'The forgotten name will be spoken thrice',
    'Roots will crack the throne',
    'The sea keeps the first key',
    'What was sealed in salt returns in smoke',
    'The smallest hand turns the great wheel',
    'Dawn comes twice on the final day',
    'The star that falls is a door that opens'
  ] },
  { cat: 'Blessings', items: [
    'May your blade stay sharp and your word sharper',
    'Walk in the light of the everflame',
    'May the road rise and the dark recede',
    'Stone endure you, river restore you',
    'May your dice land kind',
    'Nine winds at your back',
    'May your fire never gutter',
    'The forest knows you; pass freely',
    'Honey on your tongue, iron in your spine',
    'May your dead rest and your living thrive',
    'Luck of the deep roads upon you',
    'May the moons keep count of your joys alone',
    'Bread, salt, and an open gate',
    'Go with the grain of the world',
    'May your shadow fall only on friends',
    'The hearth remembers your name'
  ] },
  { cat: 'Curses', items: [
    'May your boots always be wet',
    'A thousand years of itching',
    'May every map you read be wrong',
    'Let his gold turn to teeth',
    'May the dead borrow your voice',
    'Rust take your blade at the worst hour',
    'May your fire smoke and your ale sour',
    'Let her name be forgotten mid-song',
    'May the road forget your destination',
    'Crows shall keep your secrets and tell them',
    'May your shadow arrive before you',
    'Let every door stick and every floor creak',
    'May you count coins that are not there',
    'The wound that took this writing never closes',
    'May winter find your bones first',
    'Let him hear his name in every wind and turn'
  ] },
  { cat: 'Signs & Notices', items: [
    'The Gilded Flagon — rooms, ale, discretion',
    'Blacksmith wanted, ghosts negotiable',
    'No spellcasting before noon',
    'Potions half price — survivors only',
    'Beware of owlbear',
    'Toll: one copper, one secret',
    'Closed for plague, back by harvest',
    'Fresh bread, stale rumors',
    'Bounty: the Red Wyrm of Karst, alive or ash',
    'Apothecary — we do not ask questions',
    'Keep off the burial mounds',
    'Lost: one familiar, answers to Mordecai',
    'Free candles for the night watch',
    'The library bites back',
    'All weapons peace-bonded past this arch',
    'Mind the gap between worlds',
    'Caravan departs at first light, gods willing',
    'No refunds on prophecies'
  ] },
  { cat: 'Trail Marks & Cant', items: [
    'Safe camp beyond the split oak',
    'Water foul — carry your own',
    'The watch can be bribed at dusk',
    'Rich house, soft locks, loud dog',
    'Danger sleeps here by day',
    'Friends of the road rest free',
    'Take the left tunnel, the right one sings',
    'Tribute paid through midsummer',
    'A mark lives here — easy coin',
    'The fence works the fish market',
    'Patrols double past the ninth bell',
    'Cache below the third flagstone',
    'Trust the one with the grey feather',
    'This well speaks; do not answer',
    'Hard ground, cold host, move on',
    'The pass is watched — go by the river'
  ] },
  { cat: 'Ritual & Arcane', items: [
    'By breath, by blood, by binding word',
    'The circle holds while the candle stands',
    'Name the thing and chain the name',
    'As above is sealed, so below is kept',
    'Three drops for the door, one for the keeper',
    'The ink must dry before the moon turns',
    'Bound on the seventh day of the iron month',
    'Let no second tongue disturb this working',
    'Salt the threshold, silver the latch',
    'What is written waking is paid sleeping',
    'The sigil drinks; do not let it gorge',
    'Anchor the soul before the crossing',
    'Speak the closing word or feed the gap',
    'Five points hold the star, the star holds all',
    'Cold iron remembers its first forging',
    'The lock is a question; the key is an answer'
  ] },
  { cat: 'Riddles', items: [
    'I have keys but open no locks',
    'The more you take, the more you leave behind',
    'I speak without a mouth and hear without ears',
    'Feed me and I live, give me drink and I die',
    'What has roots that nobody sees',
    'I am always coming but never arrive',
    'The one who makes it sells it; the one who buys it never uses it',
    'What walks on four legs, then two, then three',
    'I am lighter than a feather, yet no one can hold me long',
    'Break me and I work better',
    'I follow you all day but die at night',
    'What belongs to you but others use it more',
    'The poor have me, the rich need me, eat me and you die',
    'I turn once; what is out will not get in',
    'Forward I am heavy, backward I am not',
    'I have cities but no houses, rivers but no water'
  ] },
  { cat: 'Proverbs & Sayings', items: [
    'Slow is smooth, smooth is fast',
    'The second mouse gets the cheese',
    'A dull blade cuts the hand that holds it',
    'Never haggle with a dragon',
    'The dungeon is patient; be more patient',
    'Trust the dwarf about stone, the elf about stars',
    'An open door is someone’s plan',
    'Coin spends; reputation compounds',
    'The map is not the dungeon',
    'Short rests make long lives',
    'Every treasure is a hook with gold paint',
    'When in doubt, let the rogue go first',
    'The gods help those who roll well',
    'A torch shared burns no shorter',
    'Old roads know where the bones are',
    'Better a live coward at breakfast',
    'The bard exaggerates, but rarely lies',
    'Steel wins battles; bread wins wars'
  ] }
];
